<?php
/**
 * Copyright © 2017 Ajay Makwana (ajaymakwana.mail@gmail.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Life is a code
 */
?>
<?php
/**
 * Brand brand list template
 *
 * @var $block \Ajay\Brand\Block\Brand\BrandList
 */
?>
<?php
$_brandCollection = $block->getBrandCollection();
?>
<?php if (!$_brandCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find brands matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div class="products wrapper grid products-grid">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php foreach ($_brandCollection as $_brand): ?>
                <?php echo $block->getBrandHtml($_brand) ?>
            <?php endforeach; ?>
        </ol>
    </div>

    <?php echo $block->getToolbarHtml() ?>
<?php endif; ?>
